export const users = [
  { id: 1, username: "gminette0", is_online: false },
  { id: 2, username: "fgodman1", is_online: false },
  { id: 3, username: "gjouanny2", is_online: false },
  { id: 4, username: "bchazelle3", is_online: false },
  { id: 5, username: "gturville4", is_online: true },
  { id: 6, username: "thurst5", is_online: false },
  { id: 7, username: "abeharrell6", is_online: true },
  { id: 8, username: "hpayle7", is_online: false },
  { id: 9, username: "ckayley8", is_online: true },
  { id: 10, username: "acraxford9", is_online: true },
  { id: 11, username: "psloboma", is_online: false },
  { id: 12, username: "fdashkovb", is_online: false },
  { id: 13, username: "emckeveneyc", is_online: true },
  { id: 14, username: "clengthornd", is_online: true },
  { id: 15, username: "bbooste", is_online: true },
  { id: 16, username: "rlawfullf", is_online: false },
  { id: 17, username: "oklimpkeg", is_online: false },
  { id: 18, username: "kpottingerh", is_online: true },
  { id: 19, username: "hchaffeni", is_online: false },
  { id: 20, username: "thugonnetj", is_online: true },
];
